project:
  type: website
  output-dir: docs

website:
  title: ""
  description: "Fundamentos para Inferência Causal: Matemática, Probabilidade, Inferência Estatística, Regressão e Inferência Causal"

  search: false

  navbar:
    left:
      - text: "Início"
        href: "index.html#topo"

      - text: "Curso"
        href: "index.html#curso"

      - text: "Conteúdo"
        href: "index.html#conteudo"

      - text: "Para quem"
        href: "index.html#publico"

      - text: "Pré-requisitos"
        href: "index.html#requisitos"

      - text: "Sobre"
        href: "index.html#sobre"

      - text: "Junte-se a Waitlist"
        href: "index.html#waitlist"

  page-footer:
    left: "© 2026 Caio Velasco"
    right: "Construído com ❤️"

format:
  html:
    theme: flatly
    smooth-scroll: false
    css: styles.css
