project:
  type: website
  output-dir: docs

website:
  title: ""
  description: "Fundamentos da Inferência Causal: um curso completo da base matemática e estatística"
  navbar:
    left:
      - text: "Início"
        href: "curso-completo-matematica-estatistica-fundamentos-inferencia-causal.html#topo"
      - text: "Motivação"
        href: "curso-completo-matematica-estatistica-fundamentos-inferencia-causal.html#motivacao"
      - text: "Objetivo"
        href: "curso-completo-matematica-estatistica-fundamentos-inferencia-causal.html#objetivo"
      - text: "Pré-requisitos"
        href: "curso-completo-matematica-estatistica-fundamentos-inferencia-causal.html#requisitos"
      - text: "Conteúdo"
        href: "curso-completo-matematica-estatistica-fundamentos-inferencia-causal.html#conteudo"
      - text: "Inscreva-se"
        href: "curso-completo-matematica-estatistica-fundamentos-inferencia-causal.html#formulario"
      - text: "Sobre"
        href: "curso-completo-matematica-estatistica-fundamentos-inferencia-causal.html#sobre"
  page-footer:
    left: "© 2026 Caio Velasco"
    right: "Construído com ❤️"

format:
  html:
    theme: flatly    # cosmo or litera, simplex, flatly for readability
    smooth-scroll: false
    css: styles.css